import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Instrument_Sans, Hanken_Grotesk } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const instrument = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument",
})
const hanken = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hk",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${instrument.variable} ${hanken.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
